### ISSUE TITLE
Text Language

### ISSUE THREAD

**Issue by csrordzhn** [malavbhavsar/sentimentalizer#11]
Looking at the text the gem uses for training, it seems to me it supports several languages but I would like to have official confirmation from you and the list of supported languages. Thank you for this awesome gem by the way.

**Comment by malavbhavsar** [comment]
I wish I could say that. The main principle(bayesian classifier) should work for all languages, but to make this gem work correctly for any other language there are few things that you might need to change
- stop words for the specific language https://github.com/malavbhavsar/sentimentalizer/blob/master/lib/engine/classifier.rb#L10
- language specific cleaner training data here https://github.com/malavbhavsar/sentimentalizer/tree/master/lib/data

**Comment by jusgowiturs** [comment]
Hi may I know what is the challenges does this project consist of?
I would like to participate along with u
