### ISSUE TITLE
readme.md should mention Sentimentalizer.setup

### ISSUE THREAD

**Issue by neoneye** [malavbhavsar/sentimentalizer#5]
I followed the readme, but couldn't get Sentimentalizer working.

I quickly realized that I first had to invoke `.setup`

	irb> Sentimentalizer.analyze("sentimentalizer is awesome")
	NoMethodError: undefined method `analyse' for nil:NilClass
		from /very/long/path/to/sentimentalizer.rb:15:in `analyze'
		from (irb):9
		from /another/very/long/path/irb:11:in `<main>'
	irb> Sentimentalizer.setup
	Training analyser with +ve sentiment
	+ve sentiment training complete
	Training analyser with -ve sentiment
	-ve sentiment training complete
	 => nil 
	irb> Sentimentalizer.analyze("sentimentalizer is awesome")

Perhaps mention `.setup` is necessary.

Or perhaps do lazy initialization within `.analyze`, so `.setup` is invoked when needed.

Cool piece of code. Great job.

**Comment by malavbhavsar** [comment]
Correct, `Sentimentalizer.setup` does the training of model. However, that step is already taken care of in the rails initializer you generate with `rails g sentimentalizer` :)

**Comment by neoneye** [comment]
I don't use Sentimentalizer from rails.

Instead I use it via my [GraphToy](https://github.com/neoneye/GraphToy) project.
